### ISSUE TITLE
Feature ID TS083 assigned twice

### ISSUE THREAD

**Issue by xrotwang** [cldf-datasets/hueblerstability#4]
The feature ID `TS083` is assigned to two distinct features. Is this a typo? If not, we should still try to make the ID actually unique, e.g. by adding a suffix, `TS083a` and `TS083b` or similar.

**Comment by NataliiaHue** [comment]
that's right, this is one of the features I don't use anywhere and which I wanted to remove from the raw data, but didn't come to doing it manually in all 60 data sets. I ignore it in all the analyses.
